# Pre-commit hooks for Vibe TypeScript project
# See https://pre-commit.com for more information
# Install with: `npx husky install` (already configured)
# Run manually with: `npx lint-staged` or `npm run quality`

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
        exclude: 'node_modules/'
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-case-conflict

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        exclude: '(node_modules/|dist/|coverage/)'
        additional_dependencies:
          - prettier@3.0.0

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.0.0
    hooks:
      - id: eslint
        files: \.(ts|js)$
        exclude: '(node_modules/|dist/|coverage/)'
        additional_dependencies:
          - eslint@8.57.1
          - '@typescript-eslint/eslint-plugin@5.62.0'
          - '@typescript-eslint/parser@5.62.0'

  - repo: local
    hooks:
      - id: typescript-check
        name: TypeScript type checking
        entry: npm run type-check
        language: system
        files: \.(ts|tsx)$
        pass_filenames: false

      - id: jest-tests
        name: Jest tests
        entry: npm test
        language: system
        types: [javascript, typescript]
        pass_filenames: false
        always_run: true
