name: 'Vibe Self-Hosting Workflow'
description: "Vibe's self-hosting workflows for TypeScript/Node.js development"
protocol_version: 1
project_type: 'typescript'

# Project linting configuration for Vibe
lint:
  # Naming convention patterns
  naming_conventions:
    - pattern: '^[a-z][a-zA-Z0-9]*$'
      applies_to: ['functions', 'variables']
      description: 'Use camelCase for functions and variables'
    - pattern: '^[A-Z][a-zA-Z0-9]*$'
      applies_to: ['classes', 'interfaces', 'types']
      description: 'Use PascalCase for classes, interfaces, and types'
    - pattern: '^[A-Z][A-Z0-9_]*$'
      applies_to: ['constants']
      description: 'Use CONSTANT_CASE for constants'

  # Professional language patterns that are flagged
  unprofessional_patterns:
    - "\\b(gonna|wanna|gotta)\\b"
    - '!!+' # Multiple exclamation marks
    - "\\b(awesome|cool|amazing|epic)\\b" # Overly enthusiastic language

  # Emoji usage patterns
  emoji_patterns:
    documentation:
      allowed_contexts: ['headers', 'lists', 'status_indicators']
      max_per_section: 3
    code:
      allowed: false
      exceptions: ['test_files']

# TypeScript-specific file patterns
file_patterns:
  source: ['src/**/*.ts', 'src/**/*.js']
  tests: ['tests/**/*.test.ts', '**/*.spec.ts']
  config: ['*.config.ts', '*.config.js', 'tsconfig.json', 'package.json']
  documentation: ['README.md', 'docs/**/*.md', '*.md']

# Build and development settings
build:
  output_dir: 'dist'
  include_patterns: ['src/**/*']
  exclude_patterns: ['**/*.test.ts', '**/*.spec.ts']

# Development workflow preferences
development:
  auto_format: true
  strict_typing: true
  test_framework: 'jest'
  package_manager: 'npm'
