# Vibe workflow configuration - Self-hosting development setup
project_type: "python"

# Self-hosting workflows for vibe development
workflows:
  analysis:
    triggers: ["analyze", "explore", "understand", "investigate", "structure", "review", "examine"]
    commands:
      - "find . -name '*.py' -type f | grep -v .venv | head -20"
      - "echo 'ðŸ“Š Python files found:' && find . -name '*.py' -type f | grep -v .venv | wc -l"
      - "echo 'ðŸ“ Project structure:' && tree -I '.venv|__pycache__' -L 3 2>/dev/null || find . -type d | grep -v -E '.venv|__pycache__' | head -15"
      - "echo 'ðŸ“¦ Dependencies:' && grep 'dependencies' pyproject.toml -A 10"
    description: "ðŸ” Analyze vibe project structure and dependencies"

  testing:
    triggers: ["test", "tests", "validate", "check", "verify", "coverage", "spec", "unit"]
    commands:
      - "echo 'ðŸ§ª Setting up testing environment...'"
      - "uv add --dev pytest pytest-cov pytest-mock"
      - "echo 'ðŸ“ Creating basic test structure...'"
      - "mkdir -p tests"
      - "echo 'âœ… Running self-validation tests...'"
      - "uv run python -c 'import vibe; print(\"âœ… vibe module imports successfully\")'"
      - "uv run python -m vibe.cli --version"
      - "echo 'ðŸŽ¯ Testing CLI commands...'"
      - "uv run python -m vibe.cli config-info"
    description: "ðŸ§ª Test vibe functionality and self-validation"

  quality:
    triggers: ["quality", "lint", "format", "type", "standards", "compliance", "clean"]
    commands:
      - "echo 'âœ¨ Installing quality tools...'"
      - "uv add --dev ruff mypy black isort"
      - "echo 'ðŸ”§ Running ruff format...'"
      - "uv run ruff format ."
      - "echo 'ðŸ” Running ruff check...'"
      - "uv run ruff check . --fix"
      - "echo 'ðŸ”¬ Running mypy type checking...'"
      - "uv run mypy vibe/ --ignore-missing-imports || echo 'âš ï¸ Type checking completed with issues'"
      - "echo 'ðŸ“ Checking line lengths and imports...'"
      - "uv run ruff check . --select E501,I"
    description: "âœ¨ Format code, fix linting issues, and run type checking"

  implementation:
    triggers: ["implement", "add", "create", "build", "develop", "code", "make", "feature"]
    commands:
      - "echo 'ðŸ› ï¸ Preparing development environment...'"
      - "uv sync"
      - "echo 'ðŸ”§ Installing development dependencies...'"
      - "uv add --dev pytest ruff mypy black isort"
      - "echo 'ðŸ“¦ Validating package build...'"
      - "uv build"
      - "echo 'ðŸš€ Testing installation...'"
      - "uv run python -c 'from vibe import __version__; print(f\"vibe v{__version__} ready for development\")'"
    description: "ðŸ› ï¸ Set up development environment and validate build"

  documentation:
    triggers: ["document", "docs", "readme", "explain", "guide", "help"]
    commands:
      - "echo 'ðŸ“š Generating documentation...'"
      - "echo 'ðŸ“ Updating README with current features...'"
      - "uv run python -m vibe.cli list-workflows > workflow_reference.md"
      - "echo 'ðŸ“‹ Available commands:' && uv run python -m vibe.cli --help"
      - "echo 'ðŸ” Configuration info:' && uv run python -m vibe.cli config-info"
      - "echo 'ðŸ“– Documentation updated! Check workflow_reference.md for latest workflow info.'"
    description: "ï¿½ Generate and update project documentation"

  git:
    triggers: ["commit", "push", "pull", "merge", "branch", "pr", "git", "repository", "version"]
    commands:
      - "echo 'ðŸ”„ Git workflow operations...'"
      - "git status"
      - "echo 'ðŸ“Š Recent commits:' && git log --oneline -10"
      - "echo 'ðŸŒ¿ Current branch:' && git branch --show-current"
      - "echo 'ðŸ“‹ Staged changes:' && git diff --cached --stat"
      - "echo 'ðŸ“ Unstaged changes:' && git diff --stat"
    description: "ðŸ”„ Git repository management and status"

  session:
    triggers: ["complete", "finish", "cleanup", "session", "done", "ready"]
    commands:
      - "echo 'ðŸŽ¯ Session completion workflow...'"
      - "echo 'âœ… Running final validation...'"
      - "uv run python -m vibe.cli --version"
      - "echo 'ðŸ” Final quality check...'"
      - "uv run ruff check . || echo 'âš ï¸ Found style issues'"
      - "echo 'ðŸ“¦ Build validation...'"
      - "uv build"
      - "echo 'ðŸ§¹ Cleaning up...'"
      - "find . -name '*.pyc' -delete 2>/dev/null || true"
      - "find . -name '__pycache__' -type d -exec rm -rf {} + 2>/dev/null || true"
      - "echo 'âœ¨ Session ready for commit!'"
    description: "ðŸŽ¯ Complete development session with validation and cleanup"

  mcp:
    triggers: ["mcp", "context7", "github.*mcp", "playwright", "sequential.*thinking", "ai", "tools"]
    commands:
      - "echo 'ðŸ¤– MCP tools integration for vibe development...'"
      - "echo 'ðŸ” This workflow demonstrates self-hosting - vibe managing its own AI-enhanced development'"
      - "echo 'ðŸ“‹ Available MCP capabilities:'"
      - "echo '  - Context7: Latest library documentation'"
      - "echo '  - GitHub MCP: Repository operations'"
      - "echo '  - Sequential Thinking: Complex problem solving'"
      - "uv run python -c 'print(\"ðŸŽ¯ vibe is now ready for AI-enhanced self-development!\")'"
    description: "ðŸ¤– MCP tools integration and AI-enhanced development workflows"

# Custom vibe-specific workflows
  self_test:
    triggers: ["self-test", "dogfood", "validate-self", "bootstrap"]
    commands:
      - "echo 'ðŸ”„ Self-hosting validation: vibe testing itself...'"
      - "uv run python -m vibe.cli run 'analyze the project structure'"
      - "echo 'âœ… Self-analysis complete!'"
      - "uv run python -m vibe.cli run 'check code quality and formatting'"
      - "echo 'ðŸŽ‰ Self-hosting successful! vibe can manage its own development.'"
    description: "ðŸ”„ Self-hosting validation - vibe managing itself"

  bootstrap:
    triggers: ["bootstrap", "setup", "initialize", "install"]
    commands:
      - "echo 'ðŸš€ Bootstrapping vibe development environment...'"
      - "uv sync"
      - "uv add --dev pytest ruff mypy black isort"
      - "echo 'ðŸ”§ Setting up pre-commit hooks...'"
      - "echo '#!/bin/bash' > .git/hooks/pre-commit"
      - "echo 'uv run ruff check . && uv run ruff format . --check' >> .git/hooks/pre-commit"
      - "chmod +x .git/hooks/pre-commit"
      - "echo 'âœ… Bootstrap complete! Try: vibe \"run self-test to validate setup\"'"
    description: "ðŸš€ Bootstrap complete development environment"
