name: Release Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g. 0.6.1)'
        required: false
        type: string
      pre-release:
        description: 'Create a pre-release'
        required: false
        type: boolean
        default: false

# Reduce noise from CI failures
env:
  CI: true
  VITEST_SKIP_INSTALL_CHECKS: 1
  VITE_OPTIMIZED_DEPS: false
  ROLLUP_NO_BUNDLED: true

jobs:
  validate:
    name: Validate Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          npm cache clean --force
          rm -rf node_modules package-lock.json
          npm install

      - name: Build project
        run: npm run build

      - name: Run quality checks (release-grade)
        run: npm run quality:release

      - name: Validate CLI functionality
        run: |
          node dist/src/cli.js --help
          node dist/src/cli.js config-info
          node dist/src/cli.js list-workflows

  semantic-release:
    name: Semantic Release
    runs-on: ubuntu-latest
    needs: validate
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    environment: marketplace

    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write # Required for OIDC trusted publishing

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          npm cache clean --force
          rm -rf node_modules package-lock.json
          npm install

      - name: Install semantic-release dependencies
        run: npm install --save-dev semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/exec

      - name: Build project
        run: npm run build

      - name: Ensure npm 11.5.1+ for trusted publishing
        run: npm install -g npm@latest

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Manual version override (if dispatched)
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.version
        run: |
          # Update package.json with manual version
          npm version ${{ github.event.inputs.version }} --no-git-tag-version
          git add package.json
          git commit -m "chore: manual version update to ${{ github.event.inputs.version }}"

      - name: Run semantic release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # Needed for first publish, then can switch to trusted publishing
